language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 5.7
  - hhvm
  - nightly
  
before_script:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - composer install
  - bin/composer install
  - git config --global user.name travis-ci
  - git config --global user.email travis@example.com
